project:
  type: website
  output-dir: docs

website:
  title: "AntLog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Paul9615
      - icon: linkedin
        href: https://www.linkedin.com/in/gyeong-min-gu-0183041a8
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



